services:
  spark:
    build: .
    container_name: booking-lake-spark
    volumes:
      - ./src:/app/src
      - ./data/warehouse:/app/warehouse
      - ./data/scheduler_data:/app/scheduler_data
      - ./notebooks:/app/notebooks
      - ./data/booking:/app/booking_data:ro
      - ./.cache/ivy_cache:/root/.ivy2
      - ./data/s3_local:/app/s3_local
      - ./.cache/hf_cache:/root/.cache/huggingface
    environment:
      - BOOKING_DATA_DIR=/app/booking_data
      - HF_HOME=/root/.cache/huggingface
      - SCHEDULER_DB_PATH=/app/scheduler_data/scheduler.db
      - PYTHONPATH=/app:/app/src
      - S3_LOCAL_ROOT=/app/s3_local
      - SQS_ENDPOINT_URL=http://localstack:4566
      - SQS_QUEUE_NAME=booking-property-updates
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ES_INDEX_NAME=rental_properties
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - DYNAMODB_TABLE_NAME=rental_properties
    
    ports:
      - "4040:4040"
      - "8888:8888"
    depends_on:
      - localstack
      - elasticsearch

  localstack:
    image: localstack/localstack:3.7
    container_name: booking-lake-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./data/localstack_data:/var/lib/localstack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: booking-lake-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - ./data/es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: booking-lake-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.2
    container_name: booking-lake-dynamodb
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
    ports:
      - "8001:8000"
    volumes:
      - ./data/dynamodb_data:/data

  
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: booking-lake-dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "8002:8001"
    depends_on:
      - dynamodb-local