sonar.projectKey=robiulislam99_pyspark-iceberg-booking-pipeline
sonar.organization=robiulislam99
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.ruff.reportPaths=ruff-report.json
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*_cache/**