sonar.projectKey=booking-lake
# sonar.organization=your-org      # only needed for SonarCloud, not self-hosted SonarQube
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.ruff.reportPaths=ruff-report.json
sonar.python.coverage.reportPaths=tests/coverage.xml
sonar.exclusions=**/__pycache__/**,**/*_cache/**0